variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest

stages:
  - build-eleventy
  - docker-build

build-eleventy:
  stage: build-eleventy
  image: node:latest
  cache:
    paths:
      - node_modules/
  script:

    - npm install
    - npm run build
  artifacts:
    paths:
      - _site/
  only:
    - tags

docker-build:
  services:
    - docker:dind
  stage: docker-build
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --no-cache --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker tag $IMAGE_TAG $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG_LATEST
    - docker rmi $IMAGE_TAG $IMAGE_TAG_LATEST

  only:
  - tags
