---
version: '3'
services:
  comprofix:
    container_name: comprofix
    image: registry.gitlab.comprofix.com/comprofix/website:latest
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{container_name}}.rule=Host(`comprofix.com`) || host(`www.comprofix.com`)
      - traefik.http.routers.{{container_name}}.entrypoints=https
      - traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare

networks:
  traefik:
    external: true
