---
version: '3'
services:
  comprofix:
    container_name: comprofix
    image: registry.gitlab.comprofix.com/comprofix/website:latest
    container_name: comprofix-website
    restart: unless-stopped
