---
version: '3'
services:
  comprofix:
    container_name: comprofix
    image: registry.gitlab.comprofix.com/comprofix/website:latest
    restart: unless-stopped
    networks:
      - npm_default

networks:
  npm_default:
    external: true