name: Build & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: src/

      - name: Install packages
        run: npm install

      - name: Run npm build
        run: npm run build:prod
    
      - name: Build the Docker image
        run: |
          docker login --username comprofix --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build . --file Dockerfile --tag ghcr.io/comprofix/comprofix.com:latest
          docker push ghcr.io/comprofix/comprofix.com:latest  
